baseURL = 'https://karlz.codeberg.page/'
languageCode = 'en-us'
title = 'Karl'

pygmentsuseclasses = true

disableKinds = ["taxonomy", "term"]

[build]
  list = 'always'
  publishResources = true
  render = 'always'
  [build.buildStats]
    disableTags = true

[markup]
  [markup.highlight]
    lineNos = true
    anchorLineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = 'autumn'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  [security.exec]
    allow = [ '^pandoc$' ]
