baseURL = 'https://kiyotoko.github.io/'
languageCode = 'en-us'
title = 'Kiyotoko'

pygmentsuseclasses = true

disableKinds = ["taxonomy", "term"]

[build]
  list = 'always'
  publishResources = true
  render = 'always'
  [build.buildStats]
    disableTags = true

[markup]
  [markup.highlight]
    lineNos = true
    anchorLineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = 'autumn'

[security]
  [security.exec]
    allow = [ '^pandoc$' ]
